### ISSUE TITLE
Add more primative support to xilinx_phys_netlist.py

### ISSUE THREAD

**Issue by jgoeders** [byuccl/bfasst#124]
- [x] Check whether MUXF7 pins can be reordered #132 
- [x] Check if CARRY4 pins can be swapped #132 
- [x] BUFG needs to be replaced with BUFGCTRL #140

**Comment by jgoeders** [comment]
Here is some context for the BUFG:

In *tx_impl.v*, Vivado produces:
```
  BUFG clk_IBUF_BUFG_inst
       (.I(clk_IBUF),
        .O(clk_IBUF_BUFG));
```

However, fasm2bels produces only BUFGCTRL primitives:

```

  (* KEEP, DONT_TOUCH, BEL = "BUFGCTRL" *)
  BUFGCTRL #(
    .INIT_OUT(0),
    .IS_CE0_INVERTED(0),
    .IS_CE1_INVERTED(1),
    .IS_IGNORE0_INVERTED(1),
    .IS_IGNORE1_INVERTED(0),
    .IS_S0_INVERTED(0),
    .IS_S1_INVERTED(1),
    .PRESELECT_I0("TRUE"),
    .PRESELECT_I1("FALSE")
  ) CLK_BUFG_BOT_R_X139Y152_BUFGCTRL_X0Y0_BUFGCTRL (
.CE0(1'b1),
.CE1(1'b1),
.I0(LIOB33_X0Y127_IOB_X0Y128_I),
.I1(1'b1),
.IGNORE0(1'b1),
.IGNORE1(1'b1),
.O(CLK_BUFG_BOT_R_X139Y152_BUFGCTRL_X0Y0_O),
.S0(1'b1),
.S1(1'b1)
  );
```

So in `xilinx_phy_netlist.py`, BUFG instances need to be removed and replaced with the equivalent BUFGCTRL.

**Comment by jgoeders** [comment]
@palm9727, I think @reillymck may work on the BUFG, so you will want to coordinate with him.  Perhaps you could work on the MUXF7 if you are wanting to work on something.... just talk to @reillymck first.
